module TestMatchesFilter
  def test_filter_matches_all
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, '<a href="/match/1">'
    assert_includes last_response.body, '<a href="/match/2">'
    assert_includes last_response.body, '<a href="/match/3">'
    assert_includes last_response.body, '<a href="/match/4">'
    assert_includes last_response.body, '<a href="/match/5">'
    assert_includes last_response.body, '<a href="/match/6">'
    assert_includes last_response.body, '<a href="/match/7">'
    assert_includes last_response.body, '<a href="/match/8">'
    assert_includes last_response.body, '<a href="/match/9">'
    assert_includes last_response.body, '<a href="/match/10">'
    assert_includes last_response.body, '<a href="/match/11">'
    assert_includes last_response.body, '<a href="/match/12">'
    assert_includes last_response.body, '<a href="/match/13">'
    assert_includes last_response.body, '<a href="/match/14">'
    assert_includes last_response.body, '<a href="/match/15">'
    assert_includes last_response.body, '<a href="/match/16">'
    assert_includes last_response.body, '<a href="/match/17">'
    assert_includes last_response.body, '<a href="/match/18">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/21">'
    assert_includes last_response.body, '<a href="/match/22">'
    assert_includes last_response.body, '<a href="/match/23">'
    assert_includes last_response.body, '<a href="/match/24">'
    assert_includes last_response.body, '<a href="/match/25">'
    assert_includes last_response.body, '<a href="/match/26">'
    assert_includes last_response.body, '<a href="/match/27">'
    assert_includes last_response.body, '<a href="/match/28">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/31">'
    assert_includes last_response.body, '<a href="/match/32">'
    assert_includes last_response.body, '<a href="/match/33">'
    assert_includes last_response.body, '<a href="/match/34">'
    assert_includes last_response.body, '<a href="/match/35">'
    assert_includes last_response.body, '<a href="/match/36">'
    assert_includes last_response.body, '<a href="/match/37">'
    assert_includes last_response.body, '<a href="/match/38">'
    assert_includes last_response.body, '<a href="/match/39">'
    assert_includes last_response.body, '<a href="/match/40">'
    assert_includes last_response.body, '<a href="/match/41">'
    assert_includes last_response.body, '<a href="/match/42">'
    assert_includes last_response.body, '<a href="/match/43">'
    assert_includes last_response.body, '<a href="/match/44">'
    assert_includes last_response.body, '<a href="/match/45">'
    assert_includes last_response.body, '<a href="/match/46">'
    assert_includes last_response.body, '<a href="/match/47">'
    assert_includes last_response.body, '<a href="/match/48">'
    assert_includes last_response.body, '<a href="/match/49">'
    assert_includes last_response.body, '<a href="/match/50">'
    assert_includes last_response.body, '<a href="/match/51">'
    assert_includes last_response.body, '<a href="/match/52">'
    assert_includes last_response.body, '<a href="/match/53">'
    assert_includes last_response.body, '<a href="/match/54">'
    assert_includes last_response.body, '<a href="/match/55">'
    assert_includes last_response.body, '<a href="/match/56">'
    assert_includes last_response.body, '<a href="/match/57">'
    assert_includes last_response.body, '<a href="/match/58">'
    assert_includes last_response.body, '<a href="/match/59">'
    assert_includes last_response.body, '<a href="/match/60">'
    assert_includes last_response.body, '<a href="/match/61">'
    assert_includes last_response.body, '<a href="/match/62">'
    assert_includes last_response.body, '<a href="/match/63">'
    assert_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_locked_down
    post '/matches/filter',
         { :match_status => 'locked_down', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, '<a href="/match/1">'
    assert_includes last_response.body, '<a href="/match/2">'
    assert_includes last_response.body, '<a href="/match/3">'
    assert_includes last_response.body, '<a href="/match/4">'
    assert_includes last_response.body, '<a href="/match/5">'
    assert_includes last_response.body, '<a href="/match/6">'
    assert_includes last_response.body, '<a href="/match/7">'
    assert_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_not_locked_down
    post '/matches/filter',
         { :match_status => 'not_locked_down', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    assert_includes last_response.body, '<a href="/match/9">'
    assert_includes last_response.body, '<a href="/match/10">'
    assert_includes last_response.body, '<a href="/match/11">'
    assert_includes last_response.body, '<a href="/match/12">'
    assert_includes last_response.body, '<a href="/match/13">'
    assert_includes last_response.body, '<a href="/match/14">'
    assert_includes last_response.body, '<a href="/match/15">'
    assert_includes last_response.body, '<a href="/match/16">'
    assert_includes last_response.body, '<a href="/match/17">'
    assert_includes last_response.body, '<a href="/match/18">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/21">'
    assert_includes last_response.body, '<a href="/match/22">'
    assert_includes last_response.body, '<a href="/match/23">'
    assert_includes last_response.body, '<a href="/match/24">'
    assert_includes last_response.body, '<a href="/match/25">'
    assert_includes last_response.body, '<a href="/match/26">'
    assert_includes last_response.body, '<a href="/match/27">'
    assert_includes last_response.body, '<a href="/match/28">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/31">'
    assert_includes last_response.body, '<a href="/match/32">'
    assert_includes last_response.body, '<a href="/match/33">'
    assert_includes last_response.body, '<a href="/match/34">'
    assert_includes last_response.body, '<a href="/match/35">'
    assert_includes last_response.body, '<a href="/match/36">'
    assert_includes last_response.body, '<a href="/match/37">'
    assert_includes last_response.body, '<a href="/match/38">'
    assert_includes last_response.body, '<a href="/match/39">'
    assert_includes last_response.body, '<a href="/match/40">'
    assert_includes last_response.body, '<a href="/match/41">'
    assert_includes last_response.body, '<a href="/match/42">'
    assert_includes last_response.body, '<a href="/match/43">'
    assert_includes last_response.body, '<a href="/match/44">'
    assert_includes last_response.body, '<a href="/match/45">'
    assert_includes last_response.body, '<a href="/match/46">'
    assert_includes last_response.body, '<a href="/match/47">'
    assert_includes last_response.body, '<a href="/match/48">'
    assert_includes last_response.body, '<a href="/match/49">'
    assert_includes last_response.body, '<a href="/match/50">'
    assert_includes last_response.body, '<a href="/match/51">'
    assert_includes last_response.body, '<a href="/match/52">'
    assert_includes last_response.body, '<a href="/match/53">'
    assert_includes last_response.body, '<a href="/match/54">'
    assert_includes last_response.body, '<a href="/match/55">'
    assert_includes last_response.body, '<a href="/match/56">'
    assert_includes last_response.body, '<a href="/match/57">'
    assert_includes last_response.body, '<a href="/match/58">'
    assert_includes last_response.body, '<a href="/match/59">'
    assert_includes last_response.body, '<a href="/match/60">'
    assert_includes last_response.body, '<a href="/match/61">'
    assert_includes last_response.body, '<a href="/match/62">'
    assert_includes last_response.body, '<a href="/match/63">'
    assert_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_predicted
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    assert_includes last_response.body, '<a href="/match/6">'
    assert_includes last_response.body, '<a href="/match/7">'
    assert_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    assert_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_not_predicted
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'not_predicted',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, '<a href="/match/1">'
    assert_includes last_response.body, '<a href="/match/2">'
    assert_includes last_response.body, '<a href="/match/3">'
    assert_includes last_response.body, '<a href="/match/4">'
    assert_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    assert_includes last_response.body, '<a href="/match/9">'
    assert_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    assert_includes last_response.body, '<a href="/match/12">'
    assert_includes last_response.body, '<a href="/match/13">'
    assert_includes last_response.body, '<a href="/match/14">'
    assert_includes last_response.body, '<a href="/match/15">'
    assert_includes last_response.body, '<a href="/match/16">'
    assert_includes last_response.body, '<a href="/match/17">'
    assert_includes last_response.body, '<a href="/match/18">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/21">'
    assert_includes last_response.body, '<a href="/match/22">'
    assert_includes last_response.body, '<a href="/match/23">'
    assert_includes last_response.body, '<a href="/match/24">'
    assert_includes last_response.body, '<a href="/match/25">'
    assert_includes last_response.body, '<a href="/match/26">'
    assert_includes last_response.body, '<a href="/match/27">'
    assert_includes last_response.body, '<a href="/match/28">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/31">'
    assert_includes last_response.body, '<a href="/match/32">'
    assert_includes last_response.body, '<a href="/match/33">'
    assert_includes last_response.body, '<a href="/match/34">'
    assert_includes last_response.body, '<a href="/match/35">'
    assert_includes last_response.body, '<a href="/match/36">'
    assert_includes last_response.body, '<a href="/match/37">'
    assert_includes last_response.body, '<a href="/match/38">'
    assert_includes last_response.body, '<a href="/match/39">'
    assert_includes last_response.body, '<a href="/match/40">'
    assert_includes last_response.body, '<a href="/match/41">'
    assert_includes last_response.body, '<a href="/match/42">'
    assert_includes last_response.body, '<a href="/match/43">'
    assert_includes last_response.body, '<a href="/match/44">'
    assert_includes last_response.body, '<a href="/match/45">'
    assert_includes last_response.body, '<a href="/match/46">'
    assert_includes last_response.body, '<a href="/match/47">'
    assert_includes last_response.body, '<a href="/match/48">'
    assert_includes last_response.body, '<a href="/match/49">'
    assert_includes last_response.body, '<a href="/match/50">'
    assert_includes last_response.body, '<a href="/match/51">'
    assert_includes last_response.body, '<a href="/match/52">'
    assert_includes last_response.body, '<a href="/match/53">'
    assert_includes last_response.body, '<a href="/match/54">'
    assert_includes last_response.body, '<a href="/match/55">'
    assert_includes last_response.body, '<a href="/match/56">'
    assert_includes last_response.body, '<a href="/match/57">'
    assert_includes last_response.body, '<a href="/match/58">'
    assert_includes last_response.body, '<a href="/match/59">'
    assert_includes last_response.body, '<a href="/match/60">'
    assert_includes last_response.body, '<a href="/match/61">'
    assert_includes last_response.body, '<a href="/match/62">'
    assert_includes last_response.body, '<a href="/match/63">'
    assert_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_group_stages
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Group Stages" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, '<a href="/match/1">'
    assert_includes last_response.body, '<a href="/match/2">'
    assert_includes last_response.body, '<a href="/match/3">'
    assert_includes last_response.body, '<a href="/match/4">'
    assert_includes last_response.body, '<a href="/match/5">'
    assert_includes last_response.body, '<a href="/match/6">'
    assert_includes last_response.body, '<a href="/match/7">'
    assert_includes last_response.body, '<a href="/match/8">'
    assert_includes last_response.body, '<a href="/match/9">'
    assert_includes last_response.body, '<a href="/match/10">'
    assert_includes last_response.body, '<a href="/match/11">'
    assert_includes last_response.body, '<a href="/match/12">'
    assert_includes last_response.body, '<a href="/match/13">'
    assert_includes last_response.body, '<a href="/match/14">'
    assert_includes last_response.body, '<a href="/match/15">'
    assert_includes last_response.body, '<a href="/match/16">'
    assert_includes last_response.body, '<a href="/match/17">'
    assert_includes last_response.body, '<a href="/match/18">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/21">'
    assert_includes last_response.body, '<a href="/match/22">'
    assert_includes last_response.body, '<a href="/match/23">'
    assert_includes last_response.body, '<a href="/match/24">'
    assert_includes last_response.body, '<a href="/match/25">'
    assert_includes last_response.body, '<a href="/match/26">'
    assert_includes last_response.body, '<a href="/match/27">'
    assert_includes last_response.body, '<a href="/match/28">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/31">'
    assert_includes last_response.body, '<a href="/match/32">'
    assert_includes last_response.body, '<a href="/match/33">'
    assert_includes last_response.body, '<a href="/match/34">'
    assert_includes last_response.body, '<a href="/match/35">'
    assert_includes last_response.body, '<a href="/match/36">'
    assert_includes last_response.body, '<a href="/match/37">'
    assert_includes last_response.body, '<a href="/match/38">'
    assert_includes last_response.body, '<a href="/match/39">'
    assert_includes last_response.body, '<a href="/match/40">'
    assert_includes last_response.body, '<a href="/match/41">'
    assert_includes last_response.body, '<a href="/match/42">'
    assert_includes last_response.body, '<a href="/match/43">'
    assert_includes last_response.body, '<a href="/match/44">'
    assert_includes last_response.body, '<a href="/match/45">'
    assert_includes last_response.body, '<a href="/match/46">'
    assert_includes last_response.body, '<a href="/match/47">'
    assert_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_round_of_16
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Round of 16" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    assert_includes last_response.body, '<a href="/match/49">'
    assert_includes last_response.body, '<a href="/match/50">'
    assert_includes last_response.body, '<a href="/match/51">'
    assert_includes last_response.body, '<a href="/match/52">'
    assert_includes last_response.body, '<a href="/match/53">'
    assert_includes last_response.body, '<a href="/match/54">'
    assert_includes last_response.body, '<a href="/match/55">'
    assert_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_quarter_finals
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Quarter Finals" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    assert_includes last_response.body, '<a href="/match/57">'
    assert_includes last_response.body, '<a href="/match/58">'
    assert_includes last_response.body, '<a href="/match/59">'
    assert_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_semi_finals
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Semi Finals" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    assert_includes last_response.body, '<a href="/match/61">'
    assert_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_3_4_place
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Third Fourth Place Play-off" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    assert_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_final
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    assert_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_group_stages_and_final
    post '/matches/filter',
         { :match_status => 'all', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Final" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    assert_includes last_response.body, '<a href="/match/1">'
    assert_includes last_response.body, '<a href="/match/2">'
    assert_includes last_response.body, '<a href="/match/3">'
    assert_includes last_response.body, '<a href="/match/4">'
    assert_includes last_response.body, '<a href="/match/5">'
    assert_includes last_response.body, '<a href="/match/6">'
    assert_includes last_response.body, '<a href="/match/7">'
    assert_includes last_response.body, '<a href="/match/8">'
    assert_includes last_response.body, '<a href="/match/9">'
    assert_includes last_response.body, '<a href="/match/10">'
    assert_includes last_response.body, '<a href="/match/11">'
    assert_includes last_response.body, '<a href="/match/12">'
    assert_includes last_response.body, '<a href="/match/13">'
    assert_includes last_response.body, '<a href="/match/14">'
    assert_includes last_response.body, '<a href="/match/15">'
    assert_includes last_response.body, '<a href="/match/16">'
    assert_includes last_response.body, '<a href="/match/17">'
    assert_includes last_response.body, '<a href="/match/18">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/21">'
    assert_includes last_response.body, '<a href="/match/22">'
    assert_includes last_response.body, '<a href="/match/23">'
    assert_includes last_response.body, '<a href="/match/24">'
    assert_includes last_response.body, '<a href="/match/25">'
    assert_includes last_response.body, '<a href="/match/26">'
    assert_includes last_response.body, '<a href="/match/27">'
    assert_includes last_response.body, '<a href="/match/28">'
    assert_includes last_response.body, '<a href="/match/29">'
    assert_includes last_response.body, '<a href="/match/20">'
    assert_includes last_response.body, '<a href="/match/31">'
    assert_includes last_response.body, '<a href="/match/32">'
    assert_includes last_response.body, '<a href="/match/33">'
    assert_includes last_response.body, '<a href="/match/34">'
    assert_includes last_response.body, '<a href="/match/35">'
    assert_includes last_response.body, '<a href="/match/36">'
    assert_includes last_response.body, '<a href="/match/37">'
    assert_includes last_response.body, '<a href="/match/38">'
    assert_includes last_response.body, '<a href="/match/39">'
    assert_includes last_response.body, '<a href="/match/40">'
    assert_includes last_response.body, '<a href="/match/41">'
    assert_includes last_response.body, '<a href="/match/42">'
    assert_includes last_response.body, '<a href="/match/43">'
    assert_includes last_response.body, '<a href="/match/44">'
    assert_includes last_response.body, '<a href="/match/45">'
    assert_includes last_response.body, '<a href="/match/46">'
    assert_includes last_response.body, '<a href="/match/47">'
    assert_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    assert_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_not_locked_down_predicted_group_stages
    post '/matches/filter',
         { :match_status => 'not_locked_down', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    refute_includes last_response.body, '<a href="/match/6">'
    refute_includes last_response.body, '<a href="/match/7">'
    refute_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    assert_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_locked_down_predicted_group_stages
    post '/matches/filter',
         { :match_status => 'locked_down', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage" },
         user_11_session

    assert_equal 200, last_response.status
    refute_includes last_response.body, '<a href="/match/1">'
    refute_includes last_response.body, '<a href="/match/2">'
    refute_includes last_response.body, '<a href="/match/3">'
    refute_includes last_response.body, '<a href="/match/4">'
    refute_includes last_response.body, '<a href="/match/5">'
    assert_includes last_response.body, '<a href="/match/6">'
    assert_includes last_response.body, '<a href="/match/7">'
    assert_includes last_response.body, '<a href="/match/8">'
    refute_includes last_response.body, '<a href="/match/9">'
    refute_includes last_response.body, '<a href="/match/10">'
    refute_includes last_response.body, '<a href="/match/11">'
    refute_includes last_response.body, '<a href="/match/12">'
    refute_includes last_response.body, '<a href="/match/13">'
    refute_includes last_response.body, '<a href="/match/14">'
    refute_includes last_response.body, '<a href="/match/15">'
    refute_includes last_response.body, '<a href="/match/16">'
    refute_includes last_response.body, '<a href="/match/17">'
    refute_includes last_response.body, '<a href="/match/18">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/21">'
    refute_includes last_response.body, '<a href="/match/22">'
    refute_includes last_response.body, '<a href="/match/23">'
    refute_includes last_response.body, '<a href="/match/24">'
    refute_includes last_response.body, '<a href="/match/25">'
    refute_includes last_response.body, '<a href="/match/26">'
    refute_includes last_response.body, '<a href="/match/27">'
    refute_includes last_response.body, '<a href="/match/28">'
    refute_includes last_response.body, '<a href="/match/29">'
    refute_includes last_response.body, '<a href="/match/20">'
    refute_includes last_response.body, '<a href="/match/31">'
    refute_includes last_response.body, '<a href="/match/32">'
    refute_includes last_response.body, '<a href="/match/33">'
    refute_includes last_response.body, '<a href="/match/34">'
    refute_includes last_response.body, '<a href="/match/35">'
    refute_includes last_response.body, '<a href="/match/36">'
    refute_includes last_response.body, '<a href="/match/37">'
    refute_includes last_response.body, '<a href="/match/38">'
    refute_includes last_response.body, '<a href="/match/39">'
    refute_includes last_response.body, '<a href="/match/40">'
    refute_includes last_response.body, '<a href="/match/41">'
    refute_includes last_response.body, '<a href="/match/42">'
    refute_includes last_response.body, '<a href="/match/43">'
    refute_includes last_response.body, '<a href="/match/44">'
    refute_includes last_response.body, '<a href="/match/45">'
    refute_includes last_response.body, '<a href="/match/46">'
    refute_includes last_response.body, '<a href="/match/47">'
    refute_includes last_response.body, '<a href="/match/48">'
    refute_includes last_response.body, '<a href="/match/49">'
    refute_includes last_response.body, '<a href="/match/50">'
    refute_includes last_response.body, '<a href="/match/51">'
    refute_includes last_response.body, '<a href="/match/52">'
    refute_includes last_response.body, '<a href="/match/53">'
    refute_includes last_response.body, '<a href="/match/54">'
    refute_includes last_response.body, '<a href="/match/55">'
    refute_includes last_response.body, '<a href="/match/56">'
    refute_includes last_response.body, '<a href="/match/57">'
    refute_includes last_response.body, '<a href="/match/58">'
    refute_includes last_response.body, '<a href="/match/59">'
    refute_includes last_response.body, '<a href="/match/60">'
    refute_includes last_response.body, '<a href="/match/61">'
    refute_includes last_response.body, '<a href="/match/62">'
    refute_includes last_response.body, '<a href="/match/63">'
    refute_includes last_response.body, '<a href="/match/64">'
  end

  def test_filter_matches_search_criteria_retained
    post '/matches/filter',
         { :match_status => 'locked_down', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage" },
         user_11_session

    body = last_response.body.gsub(/\s/, ' ').squeeze (' ')
    assert_includes body, 'value="locked_down" checked'
    assert_includes body, 'value="predicted" checked'
    assert_includes body, 'name="Group Stages" value="tournament_stage" checked'
    refute_includes body, 'name="Final" value="tournament_stage" checked'
  end

  def test_filter_matches_no_matches_returned
    post '/matches/filter',
         { :match_status => 'locked_down', :prediction_status => 'all',
           "Final" => "tournament_stage" },
         user_11_session

    assert_includes last_response.body,
                    'No matches meet your criteria, please try again!'
    refute_includes last_response.body, 'Matches List'
  end
end
