adapter:

development:
  host:
  port:
  username:
  password:
  database: jrpl_dev

test:
  host:
  port:
  username:
  password:
  database: jrpl_test

staging:
  host:
  port:
  username:
  password:
  database:

production:
  host:
  port:
  username:
  password:
  database:
