adapter:

development:
  host:
  port:
  username:
  password:
  database:

test:
  host:
  port:
  username:
  password:
  database:

Staging:
  host:
  port:
  username:
  password:
  database:

production:
  host:
  port:
  username:
  password:
  database:
