adapter: postgresql

development:
  host:
  port:
  username: 
  password:
  database: jrpl_dev

test:
  host:
  port:
  username:
  password:
  database: jrpl_test

Staging:
  host: localhost
  port: 5432
  username: jrpl_stg
  password:
  database: jrpl_stg

production:
  host: localhost
  port: 5432
  username: jrpl
  password:
  database: jrpl