require_relative '../helpers/test_helpers'

class CMSTest < Minitest::Test
  include TestIntegrationMethods

  def test_filter_matches_all
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    assert_includes body_html, '<a href="/match/1?ring='
    assert_includes body_html, '<a href="/match/2?ring='
    assert_includes body_html, '<a href="/match/3?ring='
    assert_includes body_html, '<a href="/match/4?ring='
    assert_includes body_html, '<a href="/match/5?ring='
    assert_includes body_html, '<a href="/match/6?ring='
    assert_includes body_html, '<a href="/match/7?ring='
    assert_includes body_html, '<a href="/match/8?ring='
    assert_includes body_html, '<a href="/match/9?ring='
    assert_includes body_html, '<a href="/match/10?ring='
    assert_includes body_html, '<a href="/match/11?ring='
    assert_includes body_html, '<a href="/match/12?ring='
    assert_includes body_html, '<a href="/match/13?ring='
    assert_includes body_html, '<a href="/match/14?ring='
    assert_includes body_html, '<a href="/match/15?ring='
    assert_includes body_html, '<a href="/match/16?ring='
    assert_includes body_html, '<a href="/match/17?ring='
    assert_includes body_html, '<a href="/match/18?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/21?ring='
    assert_includes body_html, '<a href="/match/22?ring='
    assert_includes body_html, '<a href="/match/23?ring='
    assert_includes body_html, '<a href="/match/24?ring='
    assert_includes body_html, '<a href="/match/25?ring='
    assert_includes body_html, '<a href="/match/26?ring='
    assert_includes body_html, '<a href="/match/27?ring='
    assert_includes body_html, '<a href="/match/28?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/31?ring='
    assert_includes body_html, '<a href="/match/32?ring='
    assert_includes body_html, '<a href="/match/33?ring='
    assert_includes body_html, '<a href="/match/34?ring='
    assert_includes body_html, '<a href="/match/35?ring='
    assert_includes body_html, '<a href="/match/36?ring='
    assert_includes body_html, '<a href="/match/37?ring='
    assert_includes body_html, '<a href="/match/38?ring='
    assert_includes body_html, '<a href="/match/39?ring='
    assert_includes body_html, '<a href="/match/40?ring='
    assert_includes body_html, '<a href="/match/41?ring='
    assert_includes body_html, '<a href="/match/42?ring='
    assert_includes body_html, '<a href="/match/43?ring='
    assert_includes body_html, '<a href="/match/44?ring='
    assert_includes body_html, '<a href="/match/45?ring='
    assert_includes body_html, '<a href="/match/46?ring='
    assert_includes body_html, '<a href="/match/47?ring='
    assert_includes body_html, '<a href="/match/48?ring='
    assert_includes body_html, '<a href="/match/49?ring='
    assert_includes body_html, '<a href="/match/50?ring='
    assert_includes body_html, '<a href="/match/51?ring='
    assert_includes body_html, '<a href="/match/52?ring='
    assert_includes body_html, '<a href="/match/53?ring='
    assert_includes body_html, '<a href="/match/54?ring='
    assert_includes body_html, '<a href="/match/55?ring='
    assert_includes body_html, '<a href="/match/56?ring='
    assert_includes body_html, '<a href="/match/57?ring='
    assert_includes body_html, '<a href="/match/58?ring='
    assert_includes body_html, '<a href="/match/59?ring='
    assert_includes body_html, '<a href="/match/60?ring='
    assert_includes body_html, '<a href="/match/61?ring='
    assert_includes body_html, '<a href="/match/62?ring='
    assert_includes body_html, '<a href="/match/63?ring='
    assert_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_locked_down
    post '/fixtures',
         { :match_status => 'locked_down', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    assert_includes body_html, '<a href="/match/1?ring='
    assert_includes body_html, '<a href="/match/2?ring='
    assert_includes body_html, '<a href="/match/3?ring='
    assert_includes body_html, '<a href="/match/4?ring='
    assert_includes body_html, '<a href="/match/5?ring='
    assert_includes body_html, '<a href="/match/6?ring='
    assert_includes body_html, '<a href="/match/7?ring='
    assert_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_not_locked_down
    post '/fixtures',
         { :match_status => 'not_locked_down', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    assert_includes body_html, '<a href="/match/9?ring='
    assert_includes body_html, '<a href="/match/10?ring='
    assert_includes body_html, '<a href="/match/11?ring='
    assert_includes body_html, '<a href="/match/12?ring='
    assert_includes body_html, '<a href="/match/13?ring='
    assert_includes body_html, '<a href="/match/14?ring='
    assert_includes body_html, '<a href="/match/15?ring='
    assert_includes body_html, '<a href="/match/16?ring='
    assert_includes body_html, '<a href="/match/17?ring='
    assert_includes body_html, '<a href="/match/18?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/21?ring='
    assert_includes body_html, '<a href="/match/22?ring='
    assert_includes body_html, '<a href="/match/23?ring='
    assert_includes body_html, '<a href="/match/24?ring='
    assert_includes body_html, '<a href="/match/25?ring='
    assert_includes body_html, '<a href="/match/26?ring='
    assert_includes body_html, '<a href="/match/27?ring='
    assert_includes body_html, '<a href="/match/28?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/31?ring='
    assert_includes body_html, '<a href="/match/32?ring='
    assert_includes body_html, '<a href="/match/33?ring='
    assert_includes body_html, '<a href="/match/34?ring='
    assert_includes body_html, '<a href="/match/35?ring='
    assert_includes body_html, '<a href="/match/36?ring='
    assert_includes body_html, '<a href="/match/37?ring='
    assert_includes body_html, '<a href="/match/38?ring='
    assert_includes body_html, '<a href="/match/39?ring='
    assert_includes body_html, '<a href="/match/40?ring='
    assert_includes body_html, '<a href="/match/41?ring='
    assert_includes body_html, '<a href="/match/42?ring='
    assert_includes body_html, '<a href="/match/43?ring='
    assert_includes body_html, '<a href="/match/44?ring='
    assert_includes body_html, '<a href="/match/45?ring='
    assert_includes body_html, '<a href="/match/46?ring='
    assert_includes body_html, '<a href="/match/47?ring='
    assert_includes body_html, '<a href="/match/48?ring='
    assert_includes body_html, '<a href="/match/49?ring='
    assert_includes body_html, '<a href="/match/50?ring='
    assert_includes body_html, '<a href="/match/51?ring='
    assert_includes body_html, '<a href="/match/52?ring='
    assert_includes body_html, '<a href="/match/53?ring='
    assert_includes body_html, '<a href="/match/54?ring='
    assert_includes body_html, '<a href="/match/55?ring='
    assert_includes body_html, '<a href="/match/56?ring='
    assert_includes body_html, '<a href="/match/57?ring='
    assert_includes body_html, '<a href="/match/58?ring='
    assert_includes body_html, '<a href="/match/59?ring='
    assert_includes body_html, '<a href="/match/60?ring='
    assert_includes body_html, '<a href="/match/61?ring='
    assert_includes body_html, '<a href="/match/62?ring='
    assert_includes body_html, '<a href="/match/63?ring='
    assert_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_predicted
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    assert_includes body_html, '<a href="/match/6?ring='
    assert_includes body_html, '<a href="/match/7?ring='
    assert_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    assert_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_not_predicted
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'not_predicted',
           "Group Stages" => "tournament_stage", "Round of 16" => "tournament_stage", "Quarter Finals" => "tournament_stage", "Semi Finals" => "tournament_stage", "Third Fourth Place Play-off" => "tournament_stage", "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    assert_includes body_html, '<a href="/match/1?ring='
    assert_includes body_html, '<a href="/match/2?ring='
    assert_includes body_html, '<a href="/match/3?ring='
    assert_includes body_html, '<a href="/match/4?ring='
    assert_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    assert_includes body_html, '<a href="/match/9?ring='
    assert_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    assert_includes body_html, '<a href="/match/12?ring='
    assert_includes body_html, '<a href="/match/13?ring='
    assert_includes body_html, '<a href="/match/14?ring='
    assert_includes body_html, '<a href="/match/15?ring='
    assert_includes body_html, '<a href="/match/16?ring='
    assert_includes body_html, '<a href="/match/17?ring='
    assert_includes body_html, '<a href="/match/18?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/21?ring='
    assert_includes body_html, '<a href="/match/22?ring='
    assert_includes body_html, '<a href="/match/23?ring='
    assert_includes body_html, '<a href="/match/24?ring='
    assert_includes body_html, '<a href="/match/25?ring='
    assert_includes body_html, '<a href="/match/26?ring='
    assert_includes body_html, '<a href="/match/27?ring='
    assert_includes body_html, '<a href="/match/28?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/31?ring='
    assert_includes body_html, '<a href="/match/32?ring='
    assert_includes body_html, '<a href="/match/33?ring='
    assert_includes body_html, '<a href="/match/34?ring='
    assert_includes body_html, '<a href="/match/35?ring='
    assert_includes body_html, '<a href="/match/36?ring='
    assert_includes body_html, '<a href="/match/37?ring='
    assert_includes body_html, '<a href="/match/38?ring='
    assert_includes body_html, '<a href="/match/39?ring='
    assert_includes body_html, '<a href="/match/40?ring='
    assert_includes body_html, '<a href="/match/41?ring='
    assert_includes body_html, '<a href="/match/42?ring='
    assert_includes body_html, '<a href="/match/43?ring='
    assert_includes body_html, '<a href="/match/44?ring='
    assert_includes body_html, '<a href="/match/45?ring='
    assert_includes body_html, '<a href="/match/46?ring='
    assert_includes body_html, '<a href="/match/47?ring='
    assert_includes body_html, '<a href="/match/48?ring='
    assert_includes body_html, '<a href="/match/49?ring='
    assert_includes body_html, '<a href="/match/50?ring='
    assert_includes body_html, '<a href="/match/51?ring='
    assert_includes body_html, '<a href="/match/52?ring='
    assert_includes body_html, '<a href="/match/53?ring='
    assert_includes body_html, '<a href="/match/54?ring='
    assert_includes body_html, '<a href="/match/55?ring='
    assert_includes body_html, '<a href="/match/56?ring='
    assert_includes body_html, '<a href="/match/57?ring='
    assert_includes body_html, '<a href="/match/58?ring='
    assert_includes body_html, '<a href="/match/59?ring='
    assert_includes body_html, '<a href="/match/60?ring='
    assert_includes body_html, '<a href="/match/61?ring='
    assert_includes body_html, '<a href="/match/62?ring='
    assert_includes body_html, '<a href="/match/63?ring='
    assert_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_group_stages
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Group Stages" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    assert_includes body_html, '<a href="/match/1?ring='
    assert_includes body_html, '<a href="/match/2?ring='
    assert_includes body_html, '<a href="/match/3?ring='
    assert_includes body_html, '<a href="/match/4?ring='
    assert_includes body_html, '<a href="/match/5?ring='
    assert_includes body_html, '<a href="/match/6?ring='
    assert_includes body_html, '<a href="/match/7?ring='
    assert_includes body_html, '<a href="/match/8?ring='
    assert_includes body_html, '<a href="/match/9?ring='
    assert_includes body_html, '<a href="/match/10?ring='
    assert_includes body_html, '<a href="/match/11?ring='
    assert_includes body_html, '<a href="/match/12?ring='
    assert_includes body_html, '<a href="/match/13?ring='
    assert_includes body_html, '<a href="/match/14?ring='
    assert_includes body_html, '<a href="/match/15?ring='
    assert_includes body_html, '<a href="/match/16?ring='
    assert_includes body_html, '<a href="/match/17?ring='
    assert_includes body_html, '<a href="/match/18?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/21?ring='
    assert_includes body_html, '<a href="/match/22?ring='
    assert_includes body_html, '<a href="/match/23?ring='
    assert_includes body_html, '<a href="/match/24?ring='
    assert_includes body_html, '<a href="/match/25?ring='
    assert_includes body_html, '<a href="/match/26?ring='
    assert_includes body_html, '<a href="/match/27?ring='
    assert_includes body_html, '<a href="/match/28?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/31?ring='
    assert_includes body_html, '<a href="/match/32?ring='
    assert_includes body_html, '<a href="/match/33?ring='
    assert_includes body_html, '<a href="/match/34?ring='
    assert_includes body_html, '<a href="/match/35?ring='
    assert_includes body_html, '<a href="/match/36?ring='
    assert_includes body_html, '<a href="/match/37?ring='
    assert_includes body_html, '<a href="/match/38?ring='
    assert_includes body_html, '<a href="/match/39?ring='
    assert_includes body_html, '<a href="/match/40?ring='
    assert_includes body_html, '<a href="/match/41?ring='
    assert_includes body_html, '<a href="/match/42?ring='
    assert_includes body_html, '<a href="/match/43?ring='
    assert_includes body_html, '<a href="/match/44?ring='
    assert_includes body_html, '<a href="/match/45?ring='
    assert_includes body_html, '<a href="/match/46?ring='
    assert_includes body_html, '<a href="/match/47?ring='
    assert_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_round_of_16
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Round of 16" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    assert_includes body_html, '<a href="/match/49?ring='
    assert_includes body_html, '<a href="/match/50?ring='
    assert_includes body_html, '<a href="/match/51?ring='
    assert_includes body_html, '<a href="/match/52?ring='
    assert_includes body_html, '<a href="/match/53?ring='
    assert_includes body_html, '<a href="/match/54?ring='
    assert_includes body_html, '<a href="/match/55?ring='
    assert_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_quarter_finals
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Quarter Finals" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    assert_includes body_html, '<a href="/match/57?ring='
    assert_includes body_html, '<a href="/match/58?ring='
    assert_includes body_html, '<a href="/match/59?ring='
    assert_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_semi_finals
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Semi Finals" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    assert_includes body_html, '<a href="/match/61?ring='
    assert_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_3_4_place
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Third Fourth Place Play-off" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    assert_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_final
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    assert_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_group_stages_and_final
    post '/fixtures',
         { :match_status => 'all', :prediction_status => 'all',
           "Group Stages" => "tournament_stage", "Final" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    assert_includes body_html, '<a href="/match/1?ring='
    assert_includes body_html, '<a href="/match/2?ring='
    assert_includes body_html, '<a href="/match/3?ring='
    assert_includes body_html, '<a href="/match/4?ring='
    assert_includes body_html, '<a href="/match/5?ring='
    assert_includes body_html, '<a href="/match/6?ring='
    assert_includes body_html, '<a href="/match/7?ring='
    assert_includes body_html, '<a href="/match/8?ring='
    assert_includes body_html, '<a href="/match/9?ring='
    assert_includes body_html, '<a href="/match/10?ring='
    assert_includes body_html, '<a href="/match/11?ring='
    assert_includes body_html, '<a href="/match/12?ring='
    assert_includes body_html, '<a href="/match/13?ring='
    assert_includes body_html, '<a href="/match/14?ring='
    assert_includes body_html, '<a href="/match/15?ring='
    assert_includes body_html, '<a href="/match/16?ring='
    assert_includes body_html, '<a href="/match/17?ring='
    assert_includes body_html, '<a href="/match/18?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/21?ring='
    assert_includes body_html, '<a href="/match/22?ring='
    assert_includes body_html, '<a href="/match/23?ring='
    assert_includes body_html, '<a href="/match/24?ring='
    assert_includes body_html, '<a href="/match/25?ring='
    assert_includes body_html, '<a href="/match/26?ring='
    assert_includes body_html, '<a href="/match/27?ring='
    assert_includes body_html, '<a href="/match/28?ring='
    assert_includes body_html, '<a href="/match/29?ring='
    assert_includes body_html, '<a href="/match/20?ring='
    assert_includes body_html, '<a href="/match/31?ring='
    assert_includes body_html, '<a href="/match/32?ring='
    assert_includes body_html, '<a href="/match/33?ring='
    assert_includes body_html, '<a href="/match/34?ring='
    assert_includes body_html, '<a href="/match/35?ring='
    assert_includes body_html, '<a href="/match/36?ring='
    assert_includes body_html, '<a href="/match/37?ring='
    assert_includes body_html, '<a href="/match/38?ring='
    assert_includes body_html, '<a href="/match/39?ring='
    assert_includes body_html, '<a href="/match/40?ring='
    assert_includes body_html, '<a href="/match/41?ring='
    assert_includes body_html, '<a href="/match/42?ring='
    assert_includes body_html, '<a href="/match/43?ring='
    assert_includes body_html, '<a href="/match/44?ring='
    assert_includes body_html, '<a href="/match/45?ring='
    assert_includes body_html, '<a href="/match/46?ring='
    assert_includes body_html, '<a href="/match/47?ring='
    assert_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    assert_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_not_locked_down_predicted_group_stages
    post '/fixtures',
         { :match_status => 'not_locked_down', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    refute_includes body_html, '<a href="/match/6?ring='
    refute_includes body_html, '<a href="/match/7?ring='
    refute_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    assert_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_locked_down_predicted_group_stages
    post '/fixtures',
         { :match_status => 'locked_down', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage" },
         non_admin_session

    assert_equal 200, last_response.status
    refute_includes body_html, '<a href="/match/1?ring='
    refute_includes body_html, '<a href="/match/2?ring='
    refute_includes body_html, '<a href="/match/3?ring='
    refute_includes body_html, '<a href="/match/4?ring='
    refute_includes body_html, '<a href="/match/5?ring='
    assert_includes body_html, '<a href="/match/6?ring='
    assert_includes body_html, '<a href="/match/7?ring='
    assert_includes body_html, '<a href="/match/8?ring='
    refute_includes body_html, '<a href="/match/9?ring='
    refute_includes body_html, '<a href="/match/10?ring='
    refute_includes body_html, '<a href="/match/11?ring='
    refute_includes body_html, '<a href="/match/12?ring='
    refute_includes body_html, '<a href="/match/13?ring='
    refute_includes body_html, '<a href="/match/14?ring='
    refute_includes body_html, '<a href="/match/15?ring='
    refute_includes body_html, '<a href="/match/16?ring='
    refute_includes body_html, '<a href="/match/17?ring='
    refute_includes body_html, '<a href="/match/18?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/21?ring='
    refute_includes body_html, '<a href="/match/22?ring='
    refute_includes body_html, '<a href="/match/23?ring='
    refute_includes body_html, '<a href="/match/24?ring='
    refute_includes body_html, '<a href="/match/25?ring='
    refute_includes body_html, '<a href="/match/26?ring='
    refute_includes body_html, '<a href="/match/27?ring='
    refute_includes body_html, '<a href="/match/28?ring='
    refute_includes body_html, '<a href="/match/29?ring='
    refute_includes body_html, '<a href="/match/20?ring='
    refute_includes body_html, '<a href="/match/31?ring='
    refute_includes body_html, '<a href="/match/32?ring='
    refute_includes body_html, '<a href="/match/33?ring='
    refute_includes body_html, '<a href="/match/34?ring='
    refute_includes body_html, '<a href="/match/35?ring='
    refute_includes body_html, '<a href="/match/36?ring='
    refute_includes body_html, '<a href="/match/37?ring='
    refute_includes body_html, '<a href="/match/38?ring='
    refute_includes body_html, '<a href="/match/39?ring='
    refute_includes body_html, '<a href="/match/40?ring='
    refute_includes body_html, '<a href="/match/41?ring='
    refute_includes body_html, '<a href="/match/42?ring='
    refute_includes body_html, '<a href="/match/43?ring='
    refute_includes body_html, '<a href="/match/44?ring='
    refute_includes body_html, '<a href="/match/45?ring='
    refute_includes body_html, '<a href="/match/46?ring='
    refute_includes body_html, '<a href="/match/47?ring='
    refute_includes body_html, '<a href="/match/48?ring='
    refute_includes body_html, '<a href="/match/49?ring='
    refute_includes body_html, '<a href="/match/50?ring='
    refute_includes body_html, '<a href="/match/51?ring='
    refute_includes body_html, '<a href="/match/52?ring='
    refute_includes body_html, '<a href="/match/53?ring='
    refute_includes body_html, '<a href="/match/54?ring='
    refute_includes body_html, '<a href="/match/55?ring='
    refute_includes body_html, '<a href="/match/56?ring='
    refute_includes body_html, '<a href="/match/57?ring='
    refute_includes body_html, '<a href="/match/58?ring='
    refute_includes body_html, '<a href="/match/59?ring='
    refute_includes body_html, '<a href="/match/60?ring='
    refute_includes body_html, '<a href="/match/61?ring='
    refute_includes body_html, '<a href="/match/62?ring='
    refute_includes body_html, '<a href="/match/63?ring='
    refute_includes body_html, '<a href="/match/64?ring='
  end

  def test_filter_matches_search_criteria_retained
    post '/fixtures',
         { :match_status => 'locked_down', :prediction_status => 'predicted',
           "Group Stages" => "tournament_stage" },
         non_admin_session

    assert_includes body_html, 'value="locked_down" checked'
    assert_includes body_html, 'value="predicted" checked'
    assert_includes body_html, 'name="Group Stages" value="tournament_stage" checked'
    refute_includes body_html, 'name="Final" value="tournament_stage" checked'
  end

  def test_filter_matches_no_matches_returned
    post '/fixtures',
         { :match_status => 'locked_down', :prediction_status => 'all',
           "Final" => "tournament_stage" },
         non_admin_session

    assert_includes body_text, 'No matches meet your criteria, please try again!'
    refute_includes body_text, 'Matches List'
  end
end
